package view;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Hash;
import model.KapcsolatDB;

/**
 * Bejelentkezési felület.
 * @author Márta Krisztián
 * @since 2022-11-17
 */
public class BejelentkezesJFrame extends javax.swing.JFrame {
    
    private KapcsolatDB kapcsolat;
    private List<String> felhasznalonevek = new ArrayList<>();

    /**
     * Creates new form Bejelentkezes.
     */
    public BejelentkezesJFrame() {
        initComponents();
        kapcsolat = new KapcsolatDB();
        felhasznalonevek = kapcsolat.felhasznalonevekLekerdez();
        System.out.println(felhasznalonevek);
    }
    
    /**
     * Regisztrációs felület megnyitása.
     */
    public void regisztracioMegnyit() {
        RegisztracioJFrame reg = new RegisztracioJFrame();
        reg.setVisible(true);
        this.setVisible(false);
    }
    
    /**
     * Bejelentkezés implementálása és validálása.
     */
    public void bejelentkezes() {
        String felhasznalonev = felhasznalonevTextField.getText();
        String jelszo = new String(jelszoPasswordField.getPassword());
        if (!felhasznalonevek.contains(felhasznalonev)) {
            JOptionPane.showMessageDialog(null, "Hibás felhasználónév!", "Sikertelen bejelentkezés", JOptionPane.ERROR_MESSAGE);
        } else {
            if (Hash.MD5(jelszo).equals(kapcsolat.felhasznaloJelszava(felhasznalonev))) {
                MenuJFrame menu = new MenuJFrame();
                menu.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Hibás jelszó!", "Sikertelen bejelentkezés", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        felhasznalonevTextField = new javax.swing.JTextField();
        jelszoPasswordField = new javax.swing.JPasswordField();
        bejelentkezesButton = new javax.swing.JButton();
        regisztracioButton = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jelszoFelfedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bejelentkezés");
        setMinimumSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        felhasznalonevTextField.setMinimumSize(new java.awt.Dimension(200, 30));
        felhasznalonevTextField.setPreferredSize(new java.awt.Dimension(200, 30));
        felhasznalonevTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                felhasznalonevTextFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 0);
        getContentPane().add(felhasznalonevTextField, gridBagConstraints);

        jelszoPasswordField.setMinimumSize(new java.awt.Dimension(200, 30));
        jelszoPasswordField.setPreferredSize(new java.awt.Dimension(200, 30));
        jelszoPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jelszoPasswordFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 0);
        getContentPane().add(jelszoPasswordField, gridBagConstraints);

        bejelentkezesButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bejelentkezesButton.setText("Bejelentkezés");
        bejelentkezesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bejelentkezesButton.setMaximumSize(new java.awt.Dimension(200, 40));
        bejelentkezesButton.setMinimumSize(new java.awt.Dimension(200, 40));
        bejelentkezesButton.setPreferredSize(new java.awt.Dimension(200, 40));
        bejelentkezesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bejelentkezesButtonMouseClicked(evt);
            }
        });
        bejelentkezesButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bejelentkezesButtonKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 0);
        getContentPane().add(bejelentkezesButton, gridBagConstraints);

        regisztracioButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        regisztracioButton.setText("Új fiók létrehozása");
        regisztracioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regisztracioButton.setMaximumSize(new java.awt.Dimension(200, 40));
        regisztracioButton.setMinimumSize(new java.awt.Dimension(200, 40));
        regisztracioButton.setPreferredSize(new java.awt.Dimension(200, 40));
        regisztracioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regisztracioButtonMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 0);
        getContentPane().add(regisztracioButton, gridBagConstraints);

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setText("ENGLIAN");
        logoLabel.setMaximumSize(new java.awt.Dimension(150, 150));
        logoLabel.setMinimumSize(new java.awt.Dimension(150, 150));
        logoLabel.setPreferredSize(new java.awt.Dimension(150, 150));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        getContentPane().add(logoLabel, gridBagConstraints);

        jLabel1.setText("Felhasználónév:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Jelszó:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(jLabel2, gridBagConstraints);

        jelszoFelfedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jelszoFelfedLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/passwordShow.png"))); // NOI18N
        jelszoFelfedLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jelszoFelfedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jelszoFelfedLabelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jelszoFelfedLabel, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regisztracioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regisztracioButtonMouseClicked
        regisztracioMegnyit();
    }//GEN-LAST:event_regisztracioButtonMouseClicked

    private void jelszoFelfedLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jelszoFelfedLabelMouseClicked
        if (jelszoPasswordField.getEchoChar() == '*') {
            jelszoPasswordField.setEchoChar((char)0);
            jelszoFelfedLabel.setIcon(new ImageIcon(getClass().getResource("/view/images/passwordHide.png")));
        } else if (jelszoPasswordField.getEchoChar() == (char)0) {
            jelszoPasswordField.setEchoChar('*');
            jelszoFelfedLabel.setIcon(new ImageIcon(getClass().getResource("/view/images/passwordShow.png")));
        }
    }//GEN-LAST:event_jelszoFelfedLabelMouseClicked

    private void bejelentkezesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bejelentkezesButtonMouseClicked
        bejelentkezes();
    }//GEN-LAST:event_bejelentkezesButtonMouseClicked

    private void bejelentkezesButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bejelentkezesButtonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bejelentkezes();
        }
    }//GEN-LAST:event_bejelentkezesButtonKeyPressed

    private void jelszoPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jelszoPasswordFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bejelentkezes();
        }
    }//GEN-LAST:event_jelszoPasswordFieldKeyPressed

    private void felhasznalonevTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_felhasznalonevTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bejelentkezes();
        }
    }//GEN-LAST:event_felhasznalonevTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BejelentkezesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BejelentkezesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BejelentkezesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BejelentkezesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BejelentkezesJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bejelentkezesButton;
    private javax.swing.JTextField felhasznalonevTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jelszoFelfedLabel;
    private javax.swing.JPasswordField jelszoPasswordField;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton regisztracioButton;
    // End of variables declaration//GEN-END:variables
}
