package view;

import model.Felhasznalo;

/**
 * Az alkalmazás menüje.
 * @author Márta Krisztián
 * @since 2023-02-28
 */
public class MenuJFrame extends javax.swing.JFrame {
    
    private Felhasznalo beFelh;

    /**
     * Creates new form MenuJFrame.
     */
    public MenuJFrame() {
        initComponents();
    }
    
    /**
     * Creates new form MenuJFrame.
     * @param f Bejelentkezett felhasználó.
     */
    public MenuJFrame(Felhasznalo f) {
        initComponents();
        beFelh = f;
        udvLabel.setText("Szia "+f.getFelhasznalonev()+"!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        udvLabel = new javax.swing.JLabel();
        szoszedetekButton = new javax.swing.JButton();
        tesztButton = new javax.swing.JButton();
        ujSzoszedetButton = new javax.swing.JButton();
        ranglistaButton = new javax.swing.JButton();
        kijelentkezesButton = new javax.swing.JButton();
        bezarasButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menü");
        setMaximumSize(new java.awt.Dimension(300, 675));
        setMinimumSize(new java.awt.Dimension(300, 675));
        setPreferredSize(new java.awt.Dimension(300, 675));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 675));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        udvLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        udvLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        udvLabel.setText("Szia, ________!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 20, 0);
        getContentPane().add(udvLabel, gridBagConstraints);

        szoszedetekButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        szoszedetekButton.setText("<html><div text-align:center>TEMATIKUS<br>SZÓSZEDETEK</div></html>\n");
        szoszedetekButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        szoszedetekButton.setMaximumSize(new java.awt.Dimension(150, 75));
        szoszedetekButton.setMinimumSize(new java.awt.Dimension(150, 75));
        szoszedetekButton.setPreferredSize(new java.awt.Dimension(150, 75));
        szoszedetekButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                szoszedetekButtonMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(szoszedetekButton, gridBagConstraints);

        tesztButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tesztButton.setText("TESZT INDÍTÁSA");
        tesztButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tesztButton.setMaximumSize(new java.awt.Dimension(150, 75));
        tesztButton.setMinimumSize(new java.awt.Dimension(150, 75));
        tesztButton.setPreferredSize(new java.awt.Dimension(150, 75));
        tesztButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tesztButtonMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(tesztButton, gridBagConstraints);

        ujSzoszedetButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ujSzoszedetButton.setText("<html>ÚJ SZÓSZEDET<br>HOZZÁADÁSA<html>");
        ujSzoszedetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ujSzoszedetButton.setMaximumSize(new java.awt.Dimension(150, 75));
        ujSzoszedetButton.setMinimumSize(new java.awt.Dimension(150, 75));
        ujSzoszedetButton.setPreferredSize(new java.awt.Dimension(150, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(ujSzoszedetButton, gridBagConstraints);

        ranglistaButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ranglistaButton.setText("RANGLISTA");
        ranglistaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ranglistaButton.setMaximumSize(new java.awt.Dimension(150, 75));
        ranglistaButton.setMinimumSize(new java.awt.Dimension(150, 75));
        ranglistaButton.setPreferredSize(new java.awt.Dimension(150, 75));
        ranglistaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ranglistaButtonMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(ranglistaButton, gridBagConstraints);

        kijelentkezesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kijelentkezesButton.setText("KIJELENTKEZÉS");
        kijelentkezesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kijelentkezesButton.setMaximumSize(new java.awt.Dimension(150, 75));
        kijelentkezesButton.setMinimumSize(new java.awt.Dimension(150, 75));
        kijelentkezesButton.setPreferredSize(new java.awt.Dimension(150, 75));
        kijelentkezesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kijelentkezesButtonMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(kijelentkezesButton, gridBagConstraints);

        bezarasButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bezarasButton.setText("BEZÁRÁS");
        bezarasButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bezarasButton.setMaximumSize(new java.awt.Dimension(150, 75));
        bezarasButton.setMinimumSize(new java.awt.Dimension(150, 75));
        bezarasButton.setPreferredSize(new java.awt.Dimension(150, 75));
        bezarasButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bezarasButtonMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(bezarasButton, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kijelentkezesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kijelentkezesButtonMouseClicked
        BejelentkezesJFrame b = new BejelentkezesJFrame();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kijelentkezesButtonMouseClicked

    private void bezarasButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bezarasButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_bezarasButtonMouseClicked

    private void szoszedetekButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_szoszedetekButtonMouseClicked
        SzoszedetekJFrame szoszedet = new SzoszedetekJFrame(beFelh);
        szoszedet.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_szoszedetekButtonMouseClicked

    private void tesztButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tesztButtonMouseClicked
        TesztJFrame teszt = new TesztJFrame(beFelh);
        teszt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tesztButtonMouseClicked

    private void ranglistaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ranglistaButtonMouseClicked
        
    }//GEN-LAST:event_ranglistaButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bezarasButton;
    private javax.swing.JButton kijelentkezesButton;
    private javax.swing.JButton ranglistaButton;
    private javax.swing.JButton szoszedetekButton;
    private javax.swing.JButton tesztButton;
    private javax.swing.JLabel udvLabel;
    private javax.swing.JButton ujSzoszedetButton;
    // End of variables declaration//GEN-END:variables
}
