package view;

/**
 * Az alkalmazás menüje.
 * @author Márta Krisztián
 * @since 2023-02-28
 */
public class MenuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuJFrame.
     */
    public MenuJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        szoszedetekButton = new javax.swing.JButton();
        tesztButton = new javax.swing.JButton();
        ujSzoszedetButton = new javax.swing.JButton();
        ranglistaButton = new javax.swing.JButton();
        kijelentkezesButton = new javax.swing.JButton();
        kilepesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(300, 600));
        setMinimumSize(new java.awt.Dimension(300, 600));
        setPreferredSize(new java.awt.Dimension(300, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        szoszedetekButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        szoszedetekButton.setText("SZÓSZEDETEK");
        szoszedetekButton.setMaximumSize(new java.awt.Dimension(150, 75));
        szoszedetekButton.setMinimumSize(new java.awt.Dimension(150, 75));
        szoszedetekButton.setPreferredSize(new java.awt.Dimension(150, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(szoszedetekButton, gridBagConstraints);

        tesztButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tesztButton.setText("TESZT INDÍTÁSA");
        tesztButton.setMaximumSize(new java.awt.Dimension(150, 75));
        tesztButton.setMinimumSize(new java.awt.Dimension(150, 75));
        tesztButton.setPreferredSize(new java.awt.Dimension(150, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(tesztButton, gridBagConstraints);

        ujSzoszedetButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ujSzoszedetButton.setText("<html>ÚJ SZÓSZEDET<br>HOZZÁADÁSA<html>");
        ujSzoszedetButton.setMaximumSize(new java.awt.Dimension(150, 75));
        ujSzoszedetButton.setMinimumSize(new java.awt.Dimension(150, 75));
        ujSzoszedetButton.setPreferredSize(new java.awt.Dimension(150, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(ujSzoszedetButton, gridBagConstraints);

        ranglistaButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ranglistaButton.setText("RANGLISTA");
        ranglistaButton.setMaximumSize(new java.awt.Dimension(150, 75));
        ranglistaButton.setMinimumSize(new java.awt.Dimension(150, 75));
        ranglistaButton.setPreferredSize(new java.awt.Dimension(150, 75));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(ranglistaButton, gridBagConstraints);

        kijelentkezesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kijelentkezesButton.setText("KIJELENTKEZÉS");
        kijelentkezesButton.setMaximumSize(new java.awt.Dimension(150, 75));
        kijelentkezesButton.setMinimumSize(new java.awt.Dimension(150, 75));
        kijelentkezesButton.setPreferredSize(new java.awt.Dimension(150, 75));
        kijelentkezesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kijelentkezesButtonMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(kijelentkezesButton, gridBagConstraints);

        kilepesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kilepesButton.setText("KILÉPÉS");
        kilepesButton.setMaximumSize(new java.awt.Dimension(150, 75));
        kilepesButton.setMinimumSize(new java.awt.Dimension(150, 75));
        kilepesButton.setPreferredSize(new java.awt.Dimension(150, 75));
        kilepesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kilepesButtonMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(kilepesButton, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kijelentkezesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kijelentkezesButtonMouseClicked
        BejelentkezesJFrame b = new BejelentkezesJFrame();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kijelentkezesButtonMouseClicked

    private void kilepesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kilepesButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_kilepesButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton kijelentkezesButton;
    private javax.swing.JButton kilepesButton;
    private javax.swing.JButton ranglistaButton;
    private javax.swing.JButton szoszedetekButton;
    private javax.swing.JButton tesztButton;
    private javax.swing.JButton ujSzoszedetButton;
    // End of variables declaration//GEN-END:variables
}
