package view;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Hash;
import model.KapcsolatDB;

/**
 * Regisztrációs felület.
 * @author Márta Krisztián
 * @since 2022-11-17
 */
public class RegisztracioJFrame extends javax.swing.JFrame {

    private KapcsolatDB kapcsolat;
    private List<String> felhasznaloknevek = new ArrayList<>();
    private List<String> emailCimek = new ArrayList<>();
    private BejelentkezesJFrame b;

    /**
     * Creates new form Regisztracio.
     */
    public RegisztracioJFrame() {
        initComponents();
        kapcsolat = new KapcsolatDB();
        felhasznaloknevek = kapcsolat.felhasznalonevekLekerdez();
        emailCimek = kapcsolat.emailCimeketLekerdez();
    }

    /**
     * Regisztráció implementálása.
     */
    public void regisztracio() {
        String email = emailTextField.getText();
        String felhasznalonev = felhasznalonevTextField.getText();
        String jelszo = new String(jelszoPasswordField.getPassword());
        String jelszoIsmet = new String(jelszoIsmetPasswordField.getPassword());
        if (!emailValidalas(email))
            JOptionPane.showMessageDialog(null, "Helyes email címet adjon meg!", "Sikertelen regisztráció", JOptionPane.ERROR_MESSAGE);
        else if (emailCimek.contains(email))
            JOptionPane.showMessageDialog(null, "Ez az e-mail cím már regisztrálva van!", "Sikertelen regisztráció", JOptionPane.ERROR_MESSAGE);
        else if (felhasznalonev.isEmpty())
            JOptionPane.showMessageDialog(null, "Felhasználónév megadása kötelező!", "Sikertelen regisztráció", JOptionPane.ERROR_MESSAGE);
        else if (felhasznaloknevek.contains(felhasznalonev))
            JOptionPane.showMessageDialog(null, "A felhasználónév már foglalt!", "Sikertelen regisztráció", JOptionPane.ERROR_MESSAGE);
        else if (!jelszo.equals(jelszoIsmet))
            JOptionPane.showMessageDialog(null, "A jelszavaknak egyezniük kell!", "Sikertelen regisztráció", JOptionPane.ERROR_MESSAGE);
        else if (!jelszoValidalas(jelszo))
            JOptionPane.showMessageDialog(null, "A jelszónak minimum 8 karakter hosszúnak kell lenni, valamint tartalmaznia kell kisbetűt, nagybetűt és számot!", "Sikertelen regisztráció", JOptionPane.ERROR_MESSAGE);
        else {
            kapcsolat.regisztracio(email, felhasznalonev, Hash.MD5(jelszo));
            JOptionPane.showMessageDialog(null, "Sikeres regisztráció!", "Sikeres regisztráció", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            b = new BejelentkezesJFrame();
            b.setVisible(true);
        }
    }
    
    /**
     * Email cím validálása.
     * @param email A validálni kívánt email cím.
     * @return Az email cím érvényessége.
     */
    public boolean emailValidalas(String email) {
        Pattern pattern = Pattern.compile("[a-z0-9]+@[a-z]+\\.[a-z]+"); 
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }
    
     /**
     * Jelszó cím validálása.
     * @param jelszo A validálni kívánt jelszó.
     * @return Az jelszó érvényessége.
     */
    public boolean jelszoValidalas(String jelszo) {
        boolean ervenyes = true;
        Pattern kisbetu = Pattern.compile("[a-z]"); 
        Pattern nagybetu = Pattern.compile("[A-Z]");
        Pattern szam = Pattern.compile("[0-9]");
        if (jelszo.length() < 8) ervenyes = false;
        if (!kisbetu.matcher(jelszo).find()) ervenyes = false;
        if (!nagybetu.matcher(jelszo).find()) ervenyes = false;
        if (!szam.matcher(jelszo).find()) ervenyes = false;
        return ervenyes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        emailTextField = new javax.swing.JTextField();
        felhasznalonevTextField = new javax.swing.JTextField();
        jelszoPasswordField = new javax.swing.JPasswordField();
        jelszoIsmetPasswordField = new javax.swing.JPasswordField();
        regisztracioButton = new javax.swing.JButton();
        bejelentkezesButton = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jelszoFelfedLabel = new javax.swing.JLabel();
        jelszoIsmetFelfedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Regisztráció");
        setMaximumSize(new java.awt.Dimension(600, 700));
        setMinimumSize(new java.awt.Dimension(600, 700));
        setPreferredSize(new java.awt.Dimension(600, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        emailTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailTextField.setMaximumSize(new java.awt.Dimension(250, 50));
        emailTextField.setMinimumSize(new java.awt.Dimension(250, 50));
        emailTextField.setPreferredSize(new java.awt.Dimension(250, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 10, 0);
        getContentPane().add(emailTextField, gridBagConstraints);

        felhasznalonevTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        felhasznalonevTextField.setMaximumSize(new java.awt.Dimension(250, 50));
        felhasznalonevTextField.setMinimumSize(new java.awt.Dimension(250, 50));
        felhasznalonevTextField.setPreferredSize(new java.awt.Dimension(250, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 10, 0);
        getContentPane().add(felhasznalonevTextField, gridBagConstraints);

        jelszoPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jelszoPasswordField.setMaximumSize(new java.awt.Dimension(250, 50));
        jelszoPasswordField.setMinimumSize(new java.awt.Dimension(250, 50));
        jelszoPasswordField.setPreferredSize(new java.awt.Dimension(250, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 10, 0);
        getContentPane().add(jelszoPasswordField, gridBagConstraints);

        jelszoIsmetPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jelszoIsmetPasswordField.setMaximumSize(new java.awt.Dimension(250, 50));
        jelszoIsmetPasswordField.setMinimumSize(new java.awt.Dimension(250, 50));
        jelszoIsmetPasswordField.setPreferredSize(new java.awt.Dimension(250, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 25, 0);
        getContentPane().add(jelszoIsmetPasswordField, gridBagConstraints);

        regisztracioButton.setBackground(new java.awt.Color(0, 153, 255));
        regisztracioButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        regisztracioButton.setForeground(new java.awt.Color(255, 255, 255));
        regisztracioButton.setText("REGISZTRÁCIÓ");
        regisztracioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regisztracioButton.setMaximumSize(new java.awt.Dimension(200, 50));
        regisztracioButton.setMinimumSize(new java.awt.Dimension(200, 50));
        regisztracioButton.setPreferredSize(new java.awt.Dimension(200, 50));
        regisztracioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regisztracioButtonMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 10, 0);
        getContentPane().add(regisztracioButton, gridBagConstraints);

        bejelentkezesButton.setBackground(Color.WHITE);
        bejelentkezesButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bejelentkezesButton.setForeground(new java.awt.Color(0, 153, 255));
        bejelentkezesButton.setText("MÁR VAN FIÓKOM");
        bejelentkezesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bejelentkezesButton.setMaximumSize(new java.awt.Dimension(200, 50));
        bejelentkezesButton.setMinimumSize(new java.awt.Dimension(200, 50));
        bejelentkezesButton.setPreferredSize(new java.awt.Dimension(200, 50));
        bejelentkezesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bejelentkezesButtonMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        getContentPane().add(bejelentkezesButton, gridBagConstraints);

        logoLabel.setFont(new java.awt.Font("Magneto", 0, 48)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(0, 153, 255));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setText("Englian");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 50, 0);
        getContentPane().add(logoLabel, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("E-mail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Felhasználónév");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Jelszó");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Jelszó ismét");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        jelszoFelfedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jelszoFelfedLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/passwordShow.png"))); // NOI18N
        jelszoFelfedLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jelszoFelfedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jelszoFelfedLabelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        getContentPane().add(jelszoFelfedLabel, gridBagConstraints);

        jelszoIsmetFelfedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jelszoIsmetFelfedLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/passwordShow.png"))); // NOI18N
        jelszoIsmetFelfedLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jelszoIsmetFelfedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jelszoIsmetFelfedLabelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        getContentPane().add(jelszoIsmetFelfedLabel, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regisztracioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regisztracioButtonMouseClicked
        regisztracio();
    }//GEN-LAST:event_regisztracioButtonMouseClicked

    private void bejelentkezesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bejelentkezesButtonMouseClicked
        this.setVisible(false);
        b = new BejelentkezesJFrame();
        b.setVisible(true);
    }//GEN-LAST:event_bejelentkezesButtonMouseClicked

    private void jelszoFelfedLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jelszoFelfedLabelMouseClicked
        if (jelszoPasswordField.getEchoChar() == '*') {
            jelszoPasswordField.setEchoChar((char)0);
            jelszoFelfedLabel.setIcon(new ImageIcon(getClass().getResource("/view/images/passwordHide.png")));
        } else if (jelszoPasswordField.getEchoChar() == (char)0) {
            jelszoPasswordField.setEchoChar('*');
            jelszoFelfedLabel.setIcon(new ImageIcon(getClass().getResource("/view/images/passwordShow.png")));
        }
    }//GEN-LAST:event_jelszoFelfedLabelMouseClicked

    private void jelszoIsmetFelfedLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jelszoIsmetFelfedLabelMouseClicked
        if (jelszoIsmetPasswordField.getEchoChar() == '*') {
            jelszoIsmetPasswordField.setEchoChar((char)0);
            jelszoIsmetFelfedLabel.setIcon(new ImageIcon(getClass().getResource("/view/images/passwordHide.png")));
        } else if (jelszoIsmetPasswordField.getEchoChar() == (char)0) {
            jelszoIsmetPasswordField.setEchoChar('*');
            jelszoIsmetFelfedLabel.setIcon(new ImageIcon(getClass().getResource("/view/images/passwordShow.png")));
        }
    }//GEN-LAST:event_jelszoIsmetFelfedLabelMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        b = new BejelentkezesJFrame();
        b.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisztracioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisztracioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisztracioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisztracioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisztracioJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bejelentkezesButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField felhasznalonevTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jelszoFelfedLabel;
    private javax.swing.JLabel jelszoIsmetFelfedLabel;
    private javax.swing.JPasswordField jelszoIsmetPasswordField;
    private javax.swing.JPasswordField jelszoPasswordField;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton regisztracioButton;
    // End of variables declaration//GEN-END:variables
}
