package view;

import java.util.ArrayList;
import java.util.Iterator;
import model.Felhasznalo;
import model.KapcsolatDB;
import model.Szo;
import model.Temakor;

/**
 * Szószedetek és szavak szerkesztésére alkalmas felület.
 * @author Márta Krisztián
 * @since 2023-03-18
 */
public class SzerkesztoJFrame extends javax.swing.JFrame {

    private Felhasznalo beFelh;
    private KapcsolatDB kapcsolat;
    private ArrayList<Temakor> temakorok;
    private ArrayList<Szo> szavak;
    
    /**
     * Creates new form SzerkesztoJFrame.
     */
    public SzerkesztoJFrame() {
        initComponents();
    }
    
    /**
     * Creates new form SzerkesztoJFrame.
     * @param f  Bejelentkezett felhasználó.
     */
    public SzerkesztoJFrame(Felhasznalo f) {
        initComponents();
        beFelh = f;
        kapcsolat = new KapcsolatDB();
        temakorok = kapcsolat.temakorokLekerdez(beFelh);
        
        // a beépített témakörök kivétele, hogy azt ne lehessen szerkeszteni
        Iterator itr = temakorok.iterator();
        while (itr.hasNext()) {
            Temakor t = (Temakor)itr.next();
            if (t.isBeepitett() == true) {
                itr.remove();
            }
        }
               
        // témakörök ComboBox feltöltése
        for (Temakor t : temakorok) {
            temakorokComboBox.addItem(t.getMegnevezes());
        }
        
        // ha nincs saját témaköre a felhasználónak, akkor letiltja a beviteli mezőket és a gombokat
        if (temakorok.isEmpty()) {
            angolTextField.setEnabled(false);
            magyarTextField.setEnabled(false);
            angolTextField.setText("");
            magyarTextField.setText("");
            mentesButton.setEnabled(false);
            torlesButton.setEnabled(false);
        }
    }
    
    /**
     * SzavakCombobox nevű legördülő lista feltöltése.
     */
    public void szavakComboBoxFeltolt() {
        szavak = kapcsolat.szavakAdottTemakorbenLekerdez(temakorok.get(temakorokComboBox.getSelectedIndex()).getId());
        szavakComboBox.removeAllItems();
        for (Szo szo : szavak) {
            szavakComboBox.addItem(szo.getAngol()+" - "+szo.getMagyar());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        szerkesztoTabbedPane = new javax.swing.JTabbedPane();
        szavakSzerkesztesePanel = new javax.swing.JPanel();
        temakorokComboBox = new javax.swing.JComboBox<>();
        szavakComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        angolTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        magyarTextField = new javax.swing.JTextField();
        mentesButton = new javax.swing.JButton();
        torlesButton = new javax.swing.JButton();
        ujSzoszedetPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Szerkesztőnézet");
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        szerkesztoTabbedPane.setFocusable(false);
        szerkesztoTabbedPane.setMaximumSize(new java.awt.Dimension(800, 800));
        szerkesztoTabbedPane.setMinimumSize(new java.awt.Dimension(800, 800));
        szerkesztoTabbedPane.setPreferredSize(new java.awt.Dimension(800, 800));

        szavakSzerkesztesePanel.setFocusable(false);
        szavakSzerkesztesePanel.setLayout(new java.awt.GridBagLayout());

        temakorokComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        temakorokComboBox.setFocusable(false);
        temakorokComboBox.setMaximumSize(new java.awt.Dimension(200, 35));
        temakorokComboBox.setMinimumSize(new java.awt.Dimension(200, 35));
        temakorokComboBox.setPreferredSize(new java.awt.Dimension(200, 35));
        temakorokComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                temakorokComboBoxItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 100, 0);
        szavakSzerkesztesePanel.add(temakorokComboBox, gridBagConstraints);

        szavakComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        szavakComboBox.setFocusable(false);
        szavakComboBox.setMaximumSize(new java.awt.Dimension(300, 35));
        szavakComboBox.setMinimumSize(new java.awt.Dimension(300, 35));
        szavakComboBox.setPreferredSize(new java.awt.Dimension(300, 35));
        szavakComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                szavakComboBoxItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 200, 0);
        szavakSzerkesztesePanel.add(szavakComboBox, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Angol");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        szavakSzerkesztesePanel.add(jLabel1, gridBagConstraints);

        angolTextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        angolTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        angolTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        angolTextField.setMaximumSize(new java.awt.Dimension(250, 50));
        angolTextField.setMinimumSize(new java.awt.Dimension(250, 50));
        angolTextField.setPreferredSize(new java.awt.Dimension(250, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        szavakSzerkesztesePanel.add(angolTextField, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Magyar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        szavakSzerkesztesePanel.add(jLabel2, gridBagConstraints);

        magyarTextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        magyarTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        magyarTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        magyarTextField.setMaximumSize(new java.awt.Dimension(250, 50));
        magyarTextField.setMinimumSize(new java.awt.Dimension(250, 50));
        magyarTextField.setPreferredSize(new java.awt.Dimension(250, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 25, 0);
        szavakSzerkesztesePanel.add(magyarTextField, gridBagConstraints);

        mentesButton.setBackground(new java.awt.Color(0, 0, 255));
        mentesButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        mentesButton.setForeground(new java.awt.Color(255, 255, 255));
        mentesButton.setText("MENTÉS");
        mentesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mentesButton.setFocusable(false);
        mentesButton.setMaximumSize(new java.awt.Dimension(125, 50));
        mentesButton.setMinimumSize(new java.awt.Dimension(125, 50));
        mentesButton.setPreferredSize(new java.awt.Dimension(125, 50));
        mentesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mentesButtonMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        szavakSzerkesztesePanel.add(mentesButton, gridBagConstraints);

        torlesButton.setBackground(new java.awt.Color(255, 0, 0));
        torlesButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        torlesButton.setForeground(new java.awt.Color(255, 255, 255));
        torlesButton.setText("TÖRLÉS");
        torlesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        torlesButton.setFocusable(false);
        torlesButton.setMaximumSize(new java.awt.Dimension(125, 50));
        torlesButton.setMinimumSize(new java.awt.Dimension(125, 50));
        torlesButton.setPreferredSize(new java.awt.Dimension(125, 50));
        torlesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                torlesButtonMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        szavakSzerkesztesePanel.add(torlesButton, gridBagConstraints);

        szerkesztoTabbedPane.addTab("Szavak szerkesztése", szavakSzerkesztesePanel);

        javax.swing.GroupLayout ujSzoszedetPanelLayout = new javax.swing.GroupLayout(ujSzoszedetPanel);
        ujSzoszedetPanel.setLayout(ujSzoszedetPanelLayout);
        ujSzoszedetPanelLayout.setHorizontalGroup(
            ujSzoszedetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        ujSzoszedetPanelLayout.setVerticalGroup(
            ujSzoszedetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
        );

        szerkesztoTabbedPane.addTab("Új szószedet hozzáadása", ujSzoszedetPanel);

        getContentPane().add(szerkesztoTabbedPane, new java.awt.GridBagConstraints());

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MenuJFrame menu = new MenuJFrame(beFelh);
        menu.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void temakorokComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_temakorokComboBoxItemStateChanged
        if (temakorokComboBox.getItemCount() > 0) { // ha a témakörök ComboBoxban van elem, akkor a szavak ComboBox-ot feltölti az adott kategória szavaival
            szavakComboBoxFeltolt();
            if (szavakComboBox.getItemCount() == 0) { // ha a szavak ComboBoxban nincs elem, akkor letiltja a beviteli mezőket és a gombokat
                angolTextField.setEnabled(false);
                magyarTextField.setEnabled(false);
                angolTextField.setText("");
                magyarTextField.setText("");
                mentesButton.setEnabled(false);
                torlesButton.setEnabled(false);
            }
        }
    }//GEN-LAST:event_temakorokComboBoxItemStateChanged

    private void szavakComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_szavakComboBoxItemStateChanged
        if (szavakComboBox.getItemCount() == 0) {
            angolTextField.setEnabled(false);
            magyarTextField.setEnabled(false);
            angolTextField.setText("");
            magyarTextField.setText("");
            mentesButton.setEnabled(false);
            torlesButton.setEnabled(false);
        } else {
            angolTextField.setEnabled(true);
            magyarTextField.setEnabled(true);
            mentesButton.setEnabled(true);
            torlesButton.setEnabled(true);
            angolTextField.setText(szavak.get(szavakComboBox.getSelectedIndex()).getAngol());
            magyarTextField.setText(szavak.get(szavakComboBox.getSelectedIndex()).getMagyar());
        }
    }//GEN-LAST:event_szavakComboBoxItemStateChanged

    private void mentesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mentesButtonMouseClicked
        if (szavakComboBox.getSelectedIndex() != -1) {
            kapcsolat.szotModosit(szavak.get(szavakComboBox.getSelectedIndex()).getId(), angolTextField.getText(), magyarTextField.getText());
            szavakComboBoxFeltolt();
        }
    }//GEN-LAST:event_mentesButtonMouseClicked

    private void torlesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_torlesButtonMouseClicked
        if (szavakComboBox.getSelectedIndex() != -1) {
            kapcsolat.szoTorles(szavak.get(szavakComboBox.getSelectedIndex()).getId());
            szavakComboBoxFeltolt();
        }
    }//GEN-LAST:event_torlesButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SzerkesztoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SzerkesztoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SzerkesztoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SzerkesztoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SzerkesztoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angolTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField magyarTextField;
    private javax.swing.JButton mentesButton;
    private javax.swing.JComboBox<String> szavakComboBox;
    private javax.swing.JPanel szavakSzerkesztesePanel;
    private javax.swing.JTabbedPane szerkesztoTabbedPane;
    private javax.swing.JComboBox<String> temakorokComboBox;
    private javax.swing.JButton torlesButton;
    private javax.swing.JPanel ujSzoszedetPanel;
    // End of variables declaration//GEN-END:variables
}
