package view;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Felhasznalo;
import model.KapcsolatDB;
import model.Szo;
import model.Temakor;

/**
 * @todo
 * @author Márta Krisztián
 * @since 2023-03-15
 */
public class TesztJFrame extends javax.swing.JFrame {
    
    private Felhasznalo beFelh;
    private Temakor tesztTemakor;
    private KapcsolatDB kapcsolat;
    private boolean kifejezesAngol; // A kifejezés nyelve
    private List<Temakor> temakorok;
    private List<Szo> szavak;
    private List<String> kifejezesek;
    private List<String> definiciok;
//    private int hanyadikSzo; // Nem index, hanem sorszám
//    private int tudta;

    /**
     * Creates new form SzavakJFrame.
     */
    public TesztJFrame() {
        initComponents();
    }
    
    /**
     * Creates new form TesztJFrame.
     * @param f Bejelentkezett felhasználó.
     */
    public TesztJFrame(Felhasznalo f) {
        initComponents();
        tesztPanel.setVisible(false);
        vegePanel.setVisible(false);
        beFelh = f;
        kapcsolat = new KapcsolatDB();
        kifejezesAngol = angolRadioButtonKijelolve();
        temakorok = kapcsolat.temakorokLekerdez(beFelh);
        temakorokComboBoxFeltolt();
        kifejezesek = new ArrayList<>();
        definiciok = new ArrayList<>();
    }
    
    /**
     * Megvizsgálja, hogy az angol rádiógomb van-e kijelölve.
     * @return A rádiógomb kijelöltségével.
     */
    public boolean angolRadioButtonKijelolve() {
        boolean b = false;
        if (angolRadioButton.isSelected()) b = true;
        return b;
    }
    
    /**
     * A kifejezéseket és a definíciókat tartalmazó listák tartalmának beállítása.
     */
    public void kifejezesekEsDefiniciokBeallitasa() {
        kifejezesek.clear();
        definiciok.clear();
        for (Szo szo : szavak) {
            if (kifejezesAngol) {
                kifejezesek.add(szo.getAngol());
                definiciok.add(szo.getMagyar());
            } else {
                kifejezesek.add(szo.getMagyar());
                definiciok.add(szo.getAngol());
            }
        }
    }
    
    /**
     * Hozzáadja a témaköröket a legördülő listához.
     */
    public void temakorokComboBoxFeltolt() {
        for (Temakor t : temakorok) {
            temakorokComboBox.addItem(t.getMegnevezes());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        kifejezesNyelveButtonGroup = new javax.swing.ButtonGroup();
        inditasPanel = new javax.swing.JPanel();
        angolRadioButton = new javax.swing.JRadioButton();
        magyarRadioButton = new javax.swing.JRadioButton();
        temakorokComboBox = new javax.swing.JComboBox<>();
        kezdesButton = new javax.swing.JButton();
        tesztPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        vegePanel = new javax.swing.JPanel();
        ujraButton = new javax.swing.JButton();
        bezarasButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 700));
        setSize(new java.awt.Dimension(600, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        inditasPanel.setMaximumSize(new java.awt.Dimension(600, 700));
        inditasPanel.setMinimumSize(new java.awt.Dimension(600, 700));
        inditasPanel.setName(""); // NOI18N
        inditasPanel.setPreferredSize(new java.awt.Dimension(600, 700));
        inditasPanel.setLayout(new java.awt.GridBagLayout());

        kifejezesNyelveButtonGroup.add(angolRadioButton);
        angolRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        angolRadioButton.setSelected(true);
        angolRadioButton.setText("Angol");
        angolRadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        angolRadioButton.setFocusable(false);
        angolRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                angolRadioButtonItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 50, 0);
        inditasPanel.add(angolRadioButton, gridBagConstraints);

        kifejezesNyelveButtonGroup.add(magyarRadioButton);
        magyarRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        magyarRadioButton.setText("Magyar");
        magyarRadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        magyarRadioButton.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 50, 0);
        inditasPanel.add(magyarRadioButton, gridBagConstraints);

        temakorokComboBox.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        temakorokComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        temakorokComboBox.setFocusable(false);
        temakorokComboBox.setMaximumSize(new java.awt.Dimension(200, 35));
        temakorokComboBox.setMinimumSize(new java.awt.Dimension(200, 35));
        temakorokComboBox.setPreferredSize(new java.awt.Dimension(200, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 50, 0);
        inditasPanel.add(temakorokComboBox, gridBagConstraints);

        kezdesButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        kezdesButton.setText("KEZDÉS");
        kezdesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kezdesButton.setFocusable(false);
        kezdesButton.setMaximumSize(new java.awt.Dimension(200, 100));
        kezdesButton.setMinimumSize(new java.awt.Dimension(200, 100));
        kezdesButton.setPreferredSize(new java.awt.Dimension(200, 100));
        kezdesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kezdesButtonMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        inditasPanel.add(kezdesButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(inditasPanel, gridBagConstraints);

        tesztPanel.setMaximumSize(new java.awt.Dimension(600, 700));
        tesztPanel.setMinimumSize(new java.awt.Dimension(600, 700));
        tesztPanel.setPreferredSize(new java.awt.Dimension(600, 700));
        tesztPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("jLabel1");
        tesztPanel.add(jLabel1, new java.awt.GridBagConstraints());

        jLabel2.setText("jLabel2");
        tesztPanel.add(jLabel2, new java.awt.GridBagConstraints());

        jTextField1.setText("jTextField1");
        tesztPanel.add(jTextField1, new java.awt.GridBagConstraints());

        jButton1.setText("jButton1");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tesztPanel.add(jButton1, new java.awt.GridBagConstraints());

        jButton2.setText("jButton2");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tesztPanel.add(jButton2, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(tesztPanel, gridBagConstraints);

        vegePanel.setMaximumSize(new java.awt.Dimension(600, 700));
        vegePanel.setMinimumSize(new java.awt.Dimension(600, 700));
        vegePanel.setPreferredSize(new java.awt.Dimension(600, 700));
        vegePanel.setLayout(new java.awt.GridBagLayout());

        ujraButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ujraButton.setText("ÚJRA");
        ujraButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ujraButton.setFocusable(false);
        ujraButton.setMaximumSize(new java.awt.Dimension(200, 100));
        ujraButton.setMinimumSize(new java.awt.Dimension(200, 100));
        ujraButton.setPreferredSize(new java.awt.Dimension(175, 100));
        ujraButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ujraButtonMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        vegePanel.add(ujraButton, gridBagConstraints);

        bezarasButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bezarasButton.setForeground(new java.awt.Color(255, 0, 0));
        bezarasButton.setText("BEZÁRÁS");
        bezarasButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bezarasButton.setFocusable(false);
        bezarasButton.setMaximumSize(new java.awt.Dimension(200, 100));
        bezarasButton.setMinimumSize(new java.awt.Dimension(200, 100));
        bezarasButton.setPreferredSize(new java.awt.Dimension(175, 100));
        bezarasButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bezarasButtonMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        vegePanel.add(bezarasButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(vegePanel, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MenuJFrame menu = new MenuJFrame(beFelh);
        menu.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void kezdesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kezdesButtonMouseClicked
        inditasPanel.setVisible(false);
        tesztPanel.setVisible(true);
        tesztTemakor = temakorok.get(temakorokComboBox.getSelectedIndex());
        szavak = kapcsolat.szavakAdottTemakorbenLekerdez(tesztTemakor.getId());
        System.out.println(tesztTemakor.toString()); // @todo
        System.out.println(szavak); // @todo
        Collections.shuffle(szavak);
        kifejezesekEsDefiniciokBeallitasa();
    }//GEN-LAST:event_kezdesButtonMouseClicked

    private void angolRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_angolRadioButtonItemStateChanged
       kifejezesAngol = angolRadioButtonKijelolve();
       System.out.println("ANGOL GOMB KIJELÖLVE? - "+kifejezesAngol); //@todo
    }//GEN-LAST:event_angolRadioButtonItemStateChanged

    private void bezarasButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bezarasButtonMouseClicked
        MenuJFrame menu = new MenuJFrame(beFelh);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bezarasButtonMouseClicked

    private void ujraButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ujraButtonMouseClicked
        vegePanel.setVisible(false);
        inditasPanel.setVisible(true);
    }//GEN-LAST:event_ujraButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TesztJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TesztJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TesztJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TesztJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesztJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton angolRadioButton;
    private javax.swing.JButton bezarasButton;
    private javax.swing.JPanel inditasPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton kezdesButton;
    private javax.swing.ButtonGroup kifejezesNyelveButtonGroup;
    private javax.swing.JRadioButton magyarRadioButton;
    private javax.swing.JComboBox<String> temakorokComboBox;
    private javax.swing.JPanel tesztPanel;
    private javax.swing.JButton ujraButton;
    private javax.swing.JPanel vegePanel;
    // End of variables declaration//GEN-END:variables
}
